import cors from 'cors';
import express from 'express';
import { env } from './config/env.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import performanceRoutes from './routes/performance.routes.js';
import profileRoutes from './routes/profile.routes.js';
import rewardsRoutes from './routes/rewards.routes.js';
import leaderboardRoutes from './routes/leaderboard.routes.js';
import communityRoutes from './routes/community.routes.js';
import marketplaceRoutes from './routes/marketplace.routes.js';
import bookingsRoutes from './routes/bookings.routes.js';
import authRoutes from './routes/auth.routes.js';
import stravaRoutes from './routes/strava.routes.js';
import { errorHandler, notFoundHandler } from './middleware/error.middleware.js';
import { requireAuth } from './middleware/auth.middleware.js';

const app = express();
const allowedOrigins = new Set([env.clientUrl, 'http://localhost:5173', 'http://127.0.0.1:5173']);
app.use(cors({ origin(origin, callback) { if (!origin || allowedOrigins.has(origin)) return callback(null, true); return callback(new Error(`Origin ${origin} is not allowed by CORS.`)); } }));
app.use(express.json({ limit: '1mb' }));
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'hollywood-athletics-club-backend' }));
app.use('/api/auth', authRoutes);
app.use('/api/dashboard', requireAuth, dashboardRoutes);
app.use('/api/performance', requireAuth, performanceRoutes);
app.use('/api/profile', requireAuth, profileRoutes);
app.use('/api/rewards', requireAuth, rewardsRoutes);
app.use('/api/leaderboard', requireAuth, leaderboardRoutes);
app.use('/api/community', requireAuth, communityRoutes);
app.use('/api/marketplace', requireAuth, marketplaceRoutes);
app.use('/api/bookings', requireAuth, bookingsRoutes);
app.use('/api/strava', requireAuth, stravaRoutes);
app.use(notFoundHandler);
app.use(errorHandler);
export default app;
